// <auto-generated />
using System;
using Catalog.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Catalog.Database.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    partial class CatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalog")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Catalog.Database.Entities.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowSecondItemInOrder")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_second_item_in_order");

                    b.Property<bool>("ApplicableToEmalFacades")
                        .HasColumnType("boolean")
                        .HasColumnName("applicable_to_emal_facades");

                    b.Property<bool>("ApplicableToPvhFacades")
                        .HasColumnType("boolean")
                        .HasColumnName("applicable_to_pvh_facades");

                    b.Property<bool>("ApplicableToRaskroys")
                        .HasColumnType("boolean")
                        .HasColumnName("applicable_to_raskroys");

                    b.Property<string>("Article")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("article");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<bool>("CommentOnMaterialIsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("comment_on_material_is_required");

                    b.Property<int>("Count")
                        .HasColumnType("integer")
                        .HasColumnName("count");

                    b.Property<int>("CountTypeEnum")
                        .HasColumnType("integer")
                        .HasColumnName("count_type_enum");

                    b.Property<bool>("DefaultEmalFacade")
                        .HasColumnType("boolean")
                        .HasColumnName("default_emal_facade");

                    b.Property<bool>("DefaultPvhFacade")
                        .HasColumnType("boolean")
                        .HasColumnName("default_pvh_facade");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean")
                        .HasColumnName("deleted");

                    b.Property<double>("Depth")
                        .HasColumnType("double precision")
                        .HasColumnName("depth");

                    b.Property<string>("ExternalLink")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("external_link");

                    b.Property<double>("KvM")
                        .HasColumnType("double precision")
                        .HasColumnName("kv_m");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("name");

                    b.Property<int>("OrderByCol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("order_by_col");

                    b.Property<double>("PerimetrM")
                        .HasColumnType("double precision")
                        .HasColumnName("perimetr_m");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("size");

                    b.HasKey("Id")
                        .HasName("pk_materials");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_materials_category_id");

                    b.HasIndex("OrderByCol")
                        .HasDatabaseName("ix_materials_order_by_col");

                    b.ToTable("materials", "catalog");
                });

            modelBuilder.Entity("Catalog.Database.Entities.MaterialCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ExternalLink")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("external_link");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("OrderByCol")
                        .HasColumnType("integer")
                        .HasColumnName("order_by_col");

                    b.HasKey("Id")
                        .HasName("pk_material_categories");

                    b.HasIndex("OrderByCol")
                        .IsUnique()
                        .HasDatabaseName("ix_material_categories_order_by_col");

                    b.ToTable("material_categories", "catalog");
                });

            modelBuilder.Entity("Catalog.Database.Entities.MaterialImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("data");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid")
                        .HasColumnName("guid");

                    b.Property<int>("MaterialId")
                        .HasColumnType("integer")
                        .HasColumnName("material_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_material_images");

                    b.HasIndex("MaterialId")
                        .HasDatabaseName("ix_material_images_material_id");

                    b.ToTable("material_images", "catalog");
                });

            modelBuilder.Entity("Catalog.Database.Entities.Material", b =>
                {
                    b.HasOne("Catalog.Database.Entities.MaterialCategory", "Category")
                        .WithMany("Materials")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_materials_material_categories_category_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Catalog.Database.Entities.MaterialImage", b =>
                {
                    b.HasOne("Catalog.Database.Entities.Material", "Material")
                        .WithMany("Images")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_material_images_materials_material_id");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("Catalog.Database.Entities.Material", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("Catalog.Database.Entities.MaterialCategory", b =>
                {
                    b.Navigation("Materials");
                });
#pragma warning restore 612, 618
        }
    }
}
